# Generated by Django 2.2.1 on 2019-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0003_auto_20190522_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='pattern_fil2sade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
