# Generated by Django 2.2.1 on 2019-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0007_remove_rawdata_movie_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='retinaPost',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='movie_number',
            field=models.IntegerField(null=True),
        ),
    ]
